type User @collection(name: "users") {
  full_name: String!
  email: String! @unique(index: "unique_email")
  password: String!
}

type Task @collection(name: "tasks") {
  title: String!
  description: String!
  reporter: User!
  assignee: User
}